kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin-a-ingress
  namespace: httpbin-a
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: httpbin-a.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin-a-svc
                port:
                  number: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin-b-ingress
  namespace: httpbin-b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: httpbin-b.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin-b-svc
                port:
                  number: 80
