kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kube
# See: https://github.com/kubernetes-sigs/kind/issues/3389#issuecomment-1784159342
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
  - role: worker
    extraMounts:
      - hostPath: /dev
        containerPath: /dev